---
title: "ACP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FactoMineR)
library(factoextra)
library(MASS)
library(tidyverse)
library(corrplot)
data <- read.csv("/home/baptiste.criniere/Documents/Oceane/data_long_median.csv")
data$time_ord <- factor(data$time, levels = c("Before-Surgery", "1 Week", "1 Month", "2 Months", "3 Months"))
data$group <- relevel(data$group, ref = "NG")
```

# Before-Surgery
```{r}
# On sélectionne seulement la time point Before-surgery
data1 <- data %>% filter(time == "Before-Surgery")
X1 <- data1 %>% dplyr::select(time_to_cross, number_of_errors, front_limb, all_limb)
res.pca <- PCA(X1, graph = F)
# Part de variance expliquée
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))
# Graphique des résultats
var <- get_pca_var(res.pca)
fviz_pca_var(res.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )

# Par individus
fviz_pca_ind (res.pca, col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Évite le chevauchement de texte
             )
# Par groupe
pca <- PCA(data1[,c(5:8)], graph = FALSE)
fviz_pca_ind(pca,
             geom.ind = "point", # Montre les points seulement (mais pas le "text")
             col.ind = data1$group, # colorer by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Ellipses de concentration
             legend.title = "Groups"
             )
```

#  3 months
```{r}
# On sélectionne seulement la time point Before-surgery
data2 <- data %>% filter(time == "3 Months")
data2 <- data2 %>% mutate(sqrt_nb_errors = sqrt(number_of_errors))
X2 <- data2 %>% dplyr::select(time_to_cross, sqrt_nb_errors, front_limb, all_limb)
res.pca <- PCA(X2, graph = F)
# Part de variance expliquée
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))
# Graphique des résultats
var <- get_pca_var(res.pca)
fviz_pca_var(res.pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")
             )

# Par individus
fviz_pca_ind (res.pca, col.ind = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Évite le chevauchement de texte
             )
# Par groupe
pca <- PCA(data2[,c(5,7,8,11)], graph = FALSE)
fviz_pca_ind(pca,
             geom.ind = "point", # Montre les points seulement (mais pas le "text")
             col.ind = data2$group, # colorer by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, # Ellipses de concentration
             legend.title = "Groups"
             )
```

# AFD
```{r}
data2 <- data %>% filter(time == "3 Months")
data2 <- data2 %>% mutate(sqrt_nb_errors = sqrt(number_of_errors))
X2 <- data2 %>% dplyr::select(time_to_cross, sqrt_nb_errors, front_limb, all_limb, group)
model <- lda(group~., data = X2)
predictions <- model %>% predict(X2)
dd <- cbind(data2, predict(model)$x)
p <- ggplot(dd, aes(x= LD1, y = LD2, text = mouse)) +
  geom_point(aes(color = group))+
  theme_classic() +
  scale_color_manual(values=c("olivedrab1", "mediumslateblue", "red3"))

l <- plotly::ggplotly(p, tooltip="text")
htmltools::tagList(l)


```

# AFM
Virer 
```{r}
# http://www.sthda.com/french/articles/38-methodes-des-composantes-principales-dans-r-guide-pratique/77-afm-analyse-factorielle-multiple-avec-r-l-essentiel/
`%ni%` <- Negate(`%in%`)
data2 <- data %>% filter(mouse %ni% c(6,2,27))
data2 <- data2 %>% filter(time %ni% c("Before-Surgery", "1 Week"))
data2 <- data2 %>% mutate(sqrt = sqrt(number_of_errors))
data2 <- data2 %>% dplyr::select(-time_ord, -donnor_id, -group, -num_time, -number_of_errors)
library(tidyr)
d <- data2 %>% 
     gather(key, value, -time, -mouse) %>%  
     unite(new.col, c(key, time)) %>%   
     spread(new.col, value) 

d <- merge(d, unique(data[,c("mouse", "group")]), by.x = "mouse", by.y = "mouse")
row.names(d) <- d$mouse
d <- d %>% dplyr::select(-mouse)

res.mfa <- MFA(d, 
               group = c(3, 3, 3, 3, 1), 
               type = c("c", "c", "c", "c", "n"),
               name.group = c("all_limb", "front_limb", "number_of_errors", "time_to_cross", "group"), num.group.sup = c(5),
               graph = FALSE)

eig.val <- get_eigenvalue(res.mfa)
head(eig.val)
fviz_screeplot(res.mfa)
group <- get_mfa_var(res.mfa, "group")
quanti.var <- get_mfa_var(res.mfa, "quanti.var")
fviz_mfa_var(res.mfa, "quanti.var", palette = "jco", 
             col.var.sup = "violet", repel = TRUE)

fviz_mfa_var(res.mfa, "quanti.var", palette = "jco",
             col.var.sup = "violet", repel = TRUE,
             geom = c("point"), legend = "bottom")
fviz_mfa_ind(res.mfa, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)

fviz_mfa_ind(res.mfa, 
             habillage = "group", # color by groups 
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, ellipse.type = "confidence", 
             repel = TRUE 
             ) 
```

